spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.15.133:3306/sba?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: sba
    password: xCEixJctiLwFTnzt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    context-path: /security
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
      #        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true
  


